version: '2.4'

services:
  prod: &prod
    command:
      - garage-door-automation
      - --flagfile=data/flags.txt
    image: garage-door-automation
    init: true
    mem_limit: 128M
    restart: unless-stopped
    volumes:
      - prod-data:/app/data

  write-prod:
    <<: *prod
    command:
      - line-protocol-cache-consumer
      - --flagfile=data/write-prod-flags.txt

volumes:
  prod-data:
